source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rake', '~> 10.0'
gem 'dotenv'

# Web Framework
gem 'syro', '~> 3.1'
gem 'puma'
gem 'rack_csrf'
gem 'rack', '>= 2.0'
gem 'dry-transaction'
gem 'dry-container'
gem 'dry-auto_inject'
gem 'dry-system'
gem 'shield'
gem 'mote'
gem 'tas'

# Persistence
#gem 'rom'
#gem 'rom-sql'
#gem 'pg'
#gem 'sequel_pg'

gem 'bcrypt'

group :test do
  gem 'cucumber', '~> 3.1'
  gem 'rspec', '~> 3.8'
  gem 'rack-test', '~> 1.1'
  #gem 'rom-factory', '~> 0.5'
  gem 'factis', '~> 1.0'
  gem 'simplecov', '~> 0.17'
  gem 'database_cleaner'
  gem 'capybara'
  gem 'timecop'
end
